### ISSUE TITLE
执行start.exe 报错，没有指定文件

### ISSUE THREAD

**Issue by haojunwei-hub** [HAIMACloud/HMperf#2]
![image](https://user-images.githubusercontent.com/54835391/233262457-8bdd0763-532d-4c23-a84f-bc38b92faac9.png)

**Comment by haimachl** [comment]
你的运行方式什么样的，感觉没有找到对应的romstat这个文件，这个文件是用来上传到android系统中并进行采集的核心文件。
建议用cmd的命令行方式执行。
这个没有找到文件的错误，大概率是路径不对

**Comment by haimachl** [comment]
1. 编译romstat
2. 在执行start.exe的时候指定romstat的路径，具体可以参考start.py文件中的代码

**Comment by haimachl** [comment]
closed
